FROM fedora
RUN dnf distro-sync -y &&\
    dnf group install -y "Fedora Workstation" &&\
    dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm &&\
    dnf clean all
